# Generated by Django 5.2.13 on 2026-09-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerentry",
            name="entry_type",
            field=models.CharField(
                choices=[("debit", "Débit"), ("credit", "Crédit")], max_length=16
            ),
        ),
    ]
