# Generated by Django 5.2.13 on 2026-05-22 22:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0003_order_total_amount_alter_order_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("address_text", models.CharField(max_length=500)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("geo_accuracy", models.FloatField(blank=True, null=True)),
                (
                    "geo_method",
                    models.CharField(
                        choices=[
                            ("gps", "GPS"),
                            ("manual", "Manuel"),
                            ("timeout", "Timeout"),
                            ("denied", "Refusé"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("delivery_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("assigned", "Livreur assigné"),
                            ("in_transit", "En livraison"),
                            ("delivered", "Livré"),
                            ("failed", "Échec livraison"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("assigned_to", models.CharField(blank=True, max_length=200)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("cod_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cod_collected", models.BooleanField(default=False)),
                ("cod_collected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cod_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status"], name="delivery_de_status_6efeaa_idx"
                    ),
                    models.Index(
                        fields=["order"], name="delivery_de_order_i_6d5362_idx"
                    ),
                ],
            },
        ),
    ]
