# Generated by Django 5.2.13 on 2026-07-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="audio_note",
            field=models.FileField(
                blank=True,
                help_text="Enregistrement audio de la localisation du client (WebM/OGG)",
                null=True,
                upload_to="delivery/audio/%Y/%m/%d/",
                verbose_name="Note vocale client",
            ),
        ),
    ]
