# Generated by Django 5.2.17 on 2026-09-30 08:35

import core.uploads
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_montants_fcfa_entiers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="audio_note",
            field=models.FileField(
                blank=True,
                help_text="Enregistrement audio de la localisation du client (WebM/OGG)",
                null=True,
                upload_to=core.uploads.RandomUploadPath("delivery/audio", dated=True),
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("webm", "ogg", "mp3", "m4a", "wav")
                    ),
                    core.validators.MaxFileSizeValidator(5242880),
                    core.validators.validate_audio_content,
                ],
                verbose_name="Note vocale client",
            ),
        ),
    ]
