# Generated by Django 5.2.16 on 2026-07-11 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Action"
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Entité"
                    ),
                ),
                (
                    "entity_id",
                    models.BigIntegerField(db_index=True, verbose_name="ID entité"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Métadonnées"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Acteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'audit",
                "verbose_name_plural": "Journaux d'audit",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="core_auditl_entity__244637_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="core_auditl_action_096de0_idx",
                    ),
                ],
            },
        ),
    ]
