# Generated by Django 5.2.13 on 2026-09-27 02:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(choices=[('cgu', "Conditions générales d'utilisation"), ('privacy', 'Politique de confidentialité')], max_length=20, verbose_name='Document')),
                ('version', models.CharField(max_length=20, verbose_name='Version')),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Accepté le')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Acceptation légale',
                'verbose_name_plural': 'Acceptations légales',
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['user', 'document'], name='core_legala_user_id_41f940_idx')],
            },
        ),
    ]
