# Generated by Django 5.2.13 on 2026-05-19 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_sellerprofile_public_slug"),
        ("flash_sales", "0002_flashsale_public_slug"),
        ("orders", "0002_alter_order_status"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True, editable=False, max_length=24, unique=True
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("seller", "Seller storefront"),
                            ("flash_sale", "Flash sale"),
                            ("product", "Product order link"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "target_key",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("share_count", models.PositiveIntegerField(default=0)),
                ("conversion_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flash_sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="flash_sales.flashsale",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="products.product",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="accounts.sellerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShareEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page view"),
                            ("click", "Click"),
                            ("whatsapp_share", "WhatsApp share"),
                            ("conversion", "Order conversion"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(blank=True, db_index=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="share_events",
                        to="orders.order",
                    ),
                ),
                (
                    "share_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="analytics.sharelink",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["share_link", "event_type"],
                        name="analytics_s_share_l_bb5e11_idx",
                    )
                ],
            },
        ),
    ]
