# Generated by Django 5.2.13 on 2026-05-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_populate_seller_public_slugs"),
        ("analytics", "0001_initial"),
        ("flash_sales", "0003_populate_flash_sale_public_slugs"),
        ("orders", "0002_alter_order_status"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="shareevent",
            new_name="an_se_link_type_idx",
            old_name="analytics_s_share_l_bb5e11_idx",
        ),
        migrations.AddIndex(
            model_name="shareevent",
            index=models.Index(
                fields=["share_link", "created_at"], name="an_se_link_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shareevent",
            index=models.Index(
                fields=["source", "created_at"], name="an_se_src_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sharelink",
            index=models.Index(fields=["token"], name="an_sl_token_idx"),
        ),
        migrations.AddIndex(
            model_name="sharelink",
            index=models.Index(
                fields=["link_type", "seller"], name="an_sl_type_seller_idx"
            ),
        ),
    ]
