# Generated by Django 5.2.13 on 2026-05-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flash_sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashsale",
            name="public_slug",
            field=models.SlugField(
                blank=True,
                help_text="Public URL slug for share page (/f/<slug>/).",
                max_length=80,
                unique=True,
            ),
        ),
    ]
