# Generated by Django 5.2 on 2026-07-05 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_seller_profile_bio_avatar_zones'),
        ('flash_sales', '0003_populate_flash_sale_public_slugs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashsale',
            options={'ordering': ['-start_time'], 'verbose_name': 'Vente flash', 'verbose_name_plural': 'Ventes flash'},
        ),
        migrations.AddField(
            model_name='flashsale',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='flash_sales/covers/', verbose_name='Image de couverture'),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='delivery_zone',
            field=models.CharField(blank=True, help_text='Ex: Bamako, ACI 2000, Kalaban Coura', max_length=200, verbose_name='Zone de livraison'),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='max_orders',
            field=models.IntegerField(blank=True, help_text='Laisser vide pour illimite', null=True, verbose_name='Plafond de commandes'),
        ),
        migrations.AlterField(
            model_name='flashsale',
            name='end_time',
            field=models.DateTimeField(verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='flashsale',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flash_sales', to='accounts.sellerprofile', verbose_name='Vendeur'),
        ),
        migrations.AlterField(
            model_name='flashsale',
            name='public_slug',
            field=models.SlugField(blank=True, help_text='Slug public pour la page de partage (/f/<slug>/).', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='flashsale',
            name='start_time',
            field=models.DateTimeField(verbose_name='Debut'),
        ),
        migrations.AlterField(
            model_name='flashsale',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programmee'), ('live', 'En cours'), ('closed', 'Fermee'), ('executing', 'En execution'), ('completed', 'Terminee'), ('cancelled', 'Annulee')], db_index=True, default='scheduled', max_length=16, verbose_name='Statut'),
        ),
        migrations.RunPython(
            code=lambda apps, se: apps.get_model('flash_sales', 'FlashSale').objects.filter(status='draft').update(status='scheduled'),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='flashsale',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
    ]
