# Generated by Django 5.2.13 on 2026-07-11 23:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flash_sales", "0005_saleinterest"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="saleinterest",
            new_name="flash_sales_flash_s_4bd4c8_idx",
            old_name="flash_sales_flash_s_created_idx",
        ),
    ]
