# Generated by Django 5.2.13 on 2026-07-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flash_sales", "0007_flashsale_description_audio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashsale",
            name="description_audio",
            field=models.FileField(
                blank=True,
                help_text="Enregistrement audio de la description (WebM/OGG)",
                null=True,
                upload_to="audio/sales/",
                verbose_name="Description vocale",
            ),
        ),
    ]
