# Generated by Django 5.2.13 on 2026-09-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_sales', '0010_saleinterest_reminded_at'),
        ('products', '0005_owner_and_flashsaleproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='+', through='products.FlashSaleProduct', through_fields=('flash_sale', 'product'), to='products.product'),
        ),
    ]
