# Generated by Django 5.2.13 on 2026-09-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flash_sales", "0011_owner_and_flashsaleproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashsale",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mode", "Mode"),
                    ("chaussures", "Chaussures"),
                    ("beaute", "Beauté"),
                    ("electronique", "Électronique"),
                    ("alimentation", "Alimentation"),
                    ("maison", "Maison"),
                    ("autre", "Autre"),
                ],
                help_text="Vide = type de produits de la boutique.",
                max_length=20,
                verbose_name="Type de produits",
            ),
        ),
    ]
