# Generated by Django 5.2.13 on 2026-09-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flash_sales", "0012_flashsale_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashsale",
            name="max_orders",
            field=models.IntegerField(
                blank=True,
                help_text="Laisser vide pour illimité",
                null=True,
                verbose_name="Plafond de commandes",
            ),
        ),
        migrations.AlterField(
            model_name="flashsale",
            name="start_time",
            field=models.DateTimeField(verbose_name="Début"),
        ),
        migrations.AlterField(
            model_name="flashsale",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Programmée"),
                    ("live", "En cours"),
                    ("closed", "Fermée"),
                    ("executing", "En exécution"),
                    ("completed", "Terminée"),
                    ("cancelled", "Annulée"),
                ],
                db_index=True,
                default="scheduled",
                max_length=16,
                verbose_name="Statut",
            ),
        ),
    ]
