# Generated by Django 5.2.17 on 2026-09-30 08:35

import core.uploads
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flash_sales", "0013_libelles_accentues"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashsale",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.uploads.RandomUploadPath("flash_sales/covers"),
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("jpg", "jpeg", "png", "webp", "gif")
                    ),
                    core.validators.MaxFileSizeValidator(5242880),
                    core.validators.validate_image_content,
                ],
                verbose_name="Image de couverture",
            ),
        ),
        migrations.AlterField(
            model_name="flashsale",
            name="description_audio",
            field=models.FileField(
                blank=True,
                help_text="Enregistrement audio de la description (WebM/OGG)",
                null=True,
                upload_to=core.uploads.RandomUploadPath("audio/sales"),
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("webm", "ogg", "mp3", "m4a", "wav")
                    ),
                    core.validators.MaxFileSizeValidator(5242880),
                    core.validators.validate_audio_content,
                ],
                verbose_name="Description vocale",
            ),
        ),
    ]
