# Generated by Django 5.2.17 on 2026-10-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flash_sales", "0014_alter_flashsale_cover_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleinterest",
            name="contacted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Rempli quand le vendeur marque l'inscrit comme prévenu (WhatsApp).",
                null=True,
                verbose_name="Prévenu le",
            ),
        ),
    ]
