# Generated by Django 5.2.17 on 2026-10-09 11:07

import django.db.models.deletion
import django.utils.timezone
import partners.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0007_alter_sellerprofile_avatar"),
        ("subscriptions", "0009_webhooklog_payment_nullable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nom")),
                (
                    "phone",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="4 à 12 caractères : lettres majuscules et chiffres.",
                        max_length=12,
                        unique=True,
                        verbose_name="Code du partenaire",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("seller_pilot", "Vendeur pilote"),
                            ("creator", "Créateur de contenu"),
                        ],
                        default="creator",
                        max_length=16,
                        verbose_name="Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prospect", "Prospect"),
                            ("active", "Actif"),
                            ("paused", "En pause"),
                            ("ended", "Terminé"),
                            ("slot_released", "Place libérée"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("none", "Aucune"),
                            ("trial", "Essai"),
                            ("contract", "Contrat"),
                            ("ended", "Terminée"),
                        ],
                        db_index=True,
                        default="contract",
                        help_text="Aucune, essai de 30 jours, contrat d'un an, ou terminée.",
                        max_length=8,
                        verbose_name="Phase",
                    ),
                ),
                (
                    "trial_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Début de l'essai"
                    ),
                ),
                (
                    "trial_end",
                    models.DateField(
                        blank=True,
                        help_text="Calculée : début + 30 jours.",
                        null=True,
                        verbose_name="Fin de l'essai",
                    ),
                ),
                (
                    "cite_shop_consent",
                    models.BooleanField(
                        default=False, verbose_name="Autorise à citer sa boutique"
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Boutique"
                    ),
                ),
                (
                    "is_founder",
                    models.BooleanField(default=False, verbose_name="Fondateur"),
                ),
                (
                    "contract_start",
                    models.DateField(
                        default=partners.models.today, verbose_name="Début du contrat"
                    ),
                ),
                (
                    "contract_end",
                    models.DateField(
                        blank=True,
                        help_text="Calculée : début + 12 mois.",
                        verbose_name="Fin du contrat",
                    ),
                ),
                (
                    "commission_percent",
                    models.PositiveSmallIntegerField(
                        default=partners.models.default_commission_percent,
                        help_text="Figée à la création du partenaire.",
                        verbose_name="Commission (%)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Partenaire",
                "verbose_name_plural": "Partenaires",
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("commission_percent__lte", 100)),
                        name="partner_commission_percent_lte_100",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboundMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_e164", models.CharField(max_length=20, verbose_name="Numéro")),
                (
                    "template_key",
                    models.CharField(max_length=30, verbose_name="Modèle"),
                ),
                ("body_text", models.TextField(verbose_name="Message")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opened_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Lien WhatsApp préparé le",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message préparé",
                "verbose_name_plural": "Messages préparés",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartnerAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("trial_letter", "Lettre d'essai"),
                            ("program_terms", "Conditions du programme partenaire"),
                        ],
                        max_length=16,
                        verbose_name="Document",
                    ),
                ),
                (
                    "doc_version",
                    models.CharField(max_length=10, verbose_name="Version"),
                ),
                ("text_snapshot", models.TextField(verbose_name="Texte accepté")),
                (
                    "text_sha256",
                    models.CharField(max_length=64, verbose_name="Empreinte du texte"),
                ),
                (
                    "signer_name",
                    models.CharField(max_length=160, verbose_name="Nom saisi"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Accepté le"
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Empreinte IP"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("online_checkbox", "En ligne (case cochée)"),
                            ("written_manual", "Écrite (saisie par l'équipe)"),
                        ],
                        default="online_checkbox",
                        max_length=16,
                        verbose_name="Méthode",
                    ),
                ),
                (
                    "manual_reference",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Référence de l'acceptation écrite",
                    ),
                ),
                (
                    "optional_consents",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Consentements facultatifs",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptances",
                        to="partners.partner",
                        verbose_name="Partenaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acceptation de document",
                "verbose_name_plural": "Acceptations de documents",
                "ordering": ["-accepted_at"],
            },
        ),
        migrations.CreateModel(
            name="AcceptanceInvalidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Motif (interne)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invalidated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "acceptance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invalidation",
                        to="partners.partneracceptance",
                        verbose_name="Acceptation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invalidation d'acceptation",
                "verbose_name_plural": "Invalidations d'acceptations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartnerAccessLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[("view", "Consultation"), ("accept", "Acceptation")],
                        max_length=8,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acceptance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="access_links",
                        to="partners.partneracceptance",
                        verbose_name="Acceptation obtenue avec ce lien",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_links",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien privé",
                "verbose_name_plural": "Liens privés",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartnerClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="Empreinte IP"
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="partners.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clic sur le lien",
                "verbose_name_plural": "Clics sur le lien",
            },
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        help_text="AAAA-MM", max_length=7, verbose_name="Période"
                    ),
                ),
                (
                    "total_fcfa",
                    models.PositiveIntegerField(verbose_name="Total (FCFA)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("due", "À verser"), ("paid", "Versé")],
                        db_index=True,
                        default="due",
                        max_length=8,
                    ),
                ),
                (
                    "orange_reference",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Référence Orange"
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="partners.partner",
                        verbose_name="Partenaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versement",
                "verbose_name_plural": "Versements",
                "ordering": ["-period"],
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attributed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Attribué le"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("link", "Lien"),
                            ("code", "Code saisi"),
                            ("manual", "Manuel"),
                        ],
                        default="link",
                        max_length=8,
                    ),
                ),
                ("signup_ip_hash", models.CharField(blank=True, max_length=32)),
                ("first_paid_at", models.DateTimeField(blank=True, null=True)),
                ("commission_ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "flagged",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Signalé"
                    ),
                ),
                ("flag_reason", models.CharField(blank=True, max_length=120)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referrals",
                        to="partners.partner",
                        verbose_name="Partenaire",
                    ),
                ),
                (
                    "seller",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="referral",
                        to="accounts.sellerprofile",
                        verbose_name="Vendeur inscrit via le lien",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscription via le lien",
                "verbose_name_plural": "Inscriptions via le lien",
            },
        ),
        migrations.CreateModel(
            name="CommissionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gross_fcfa",
                    models.PositiveIntegerField(verbose_name="Montant payé (FCFA)"),
                ),
                (
                    "net_fcfa",
                    models.PositiveIntegerField(
                        verbose_name="Net après retenue Orange (FCFA)"
                    ),
                ),
                (
                    "percent",
                    models.PositiveSmallIntegerField(verbose_name="Commission (%)"),
                ),
                (
                    "commission_fcfa",
                    models.PositiveIntegerField(verbose_name="Commission (FCFA)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "À valider"),
                            ("validated", "Validée"),
                            ("paid", "Versée"),
                            ("cancelled", "Annulée"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partner_commission",
                        to="subscriptions.subscriptionpayment",
                        verbose_name="Paiement d'abonnement",
                    ),
                ),
                (
                    "payout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="partners.payout",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commissions",
                        to="partners.referral",
                        verbose_name="Inscription via le lien",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commission",
                "verbose_name_plural": "Commissions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="partneracceptance",
            constraint=models.UniqueConstraint(
                fields=("partner", "doc_type", "doc_version"),
                name="acceptance_unique_doc_version",
            ),
        ),
        migrations.AddIndex(
            model_name="partnerclick",
            index=models.Index(
                fields=["partner", "created_at"], name="partners_pa_partner_aae1e0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="payout",
            constraint=models.UniqueConstraint(
                fields=("partner", "period"), name="payout_unique_partner_period"
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["partner", "attributed_at"],
                name="partners_re_partner_f19bc3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["partner", "signup_ip_hash", "attributed_at"],
                name="partners_re_partner_5629c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="commissionentry",
            index=models.Index(
                fields=["referral", "status"], name="partners_co_referra_871b1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commissionentry",
            index=models.Index(
                fields=["status", "created_at"], name="partners_co_status_0dc9a1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="commissionentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("commission_fcfa__lte", models.F("net_fcfa")),
                    ("net_fcfa__lte", models.F("gross_fcfa")),
                ),
                name="commission_amounts_consistent",
            ),
        ),
    ]
