# Generated by Django 5.2.13 on 2026-09-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_sellerprofile_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerprofile",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mode", "Mode"),
                    ("chaussures", "Chaussures"),
                    ("beaute", "Beauté"),
                    ("electronique", "Électronique"),
                    ("alimentation", "Alimentation"),
                    ("maison", "Maison"),
                    ("autre", "Autre"),
                ],
                help_text="Catégorie par défaut de vos ventes (modifiable vente par vente).",
                max_length=20,
                verbose_name="Type de produits",
            ),
        ),
    ]
