# Generated by Django 5.2.17 on 2026-09-30 08:35

import core.uploads
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_libelles_accentues"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.uploads.RandomUploadPath("sellers/avatars"),
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("jpg", "jpeg", "png", "webp")
                    ),
                    core.validators.MaxFileSizeValidator(5242880),
                    core.validators.validate_image_content,
                ],
                verbose_name="Photo de profil",
            ),
        ),
    ]
