# Generated by Django 5.2.13 on 2026-07-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_medium_plan_payment"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="subscriptionpayment",
            new_name="subscriptio_order_i_4af9d5_idx",
            old_name="sub_pay_order_idx",
        ),
        migrations.RenameIndex(
            model_name="subscriptionpayment",
            new_name="subscriptio_seller__a00b38_idx",
            old_name="sub_pay_seller_status_idx",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Null = Free perpetuel ou plan actif sans expiration",
                null=True,
                verbose_name="Expire le",
            ),
        ),
    ]
