# Generated by Django 5.2.13 on 2026-09-15 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_orange_money_security_improvements"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="subscriptionpayment",
            new_name="subscriptio_notif_t_01f95e_idx",
            old_name="subscriptions_notif_token_idx",
        ),
        migrations.RenameIndex(
            model_name="webhooklog",
            new_name="subscriptio_notif_t_c68c64_idx",
            old_name="subscriptions_notif_t_idx",
        ),
        migrations.RenameIndex(
            model_name="webhooklog",
            new_name="subscriptio_payment_2b5884_idx",
            old_name="subscriptions_payment_status_idx",
        ),
        migrations.AlterField(
            model_name="webhooklog",
            name="error_message",
            field=models.TextField(
                blank=True, help_text="Message d'erreur si le traitement a échoué"
            ),
        ),
        migrations.AlterField(
            model_name="webhooklog",
            name="payment",
            field=models.ForeignKey(
                help_text="Paiement associé (si trouvé)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhook_logs",
                to="subscriptions.subscriptionpayment",
            ),
        ),
        migrations.AlterField(
            model_name="webhooklog",
            name="processed",
            field=models.BooleanField(
                default=True,
                help_text="True si le webhook a été traité (activation ou mise à jour du paiement)",
            ),
        ),
        migrations.AlterField(
            model_name="webhooklog",
            name="raw_payload",
            field=models.JSONField(
                help_text="Payload brut reçu du webhook (sans secrets)"
            ),
        ),
        migrations.AlterField(
            model_name="webhooklog",
            name="status",
            field=models.CharField(
                blank=True,
                help_text="Statut rapporté par Orange Money (success/failure/etc)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="webhooklog",
            name="txn_id",
            field=models.CharField(
                blank=True, help_text="ID transaction Orange Money", max_length=200
            ),
        ),
    ]
