# Generated by Django 5.2.13 on 2026-09-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0005_rename_subscriptions_notif_token_idx_subscriptio_notif_t_01f95e_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Null = Free perpétuel ou plan actif sans expiration",
                null=True,
                verbose_name="Expire le",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="phone",
            field=models.CharField(help_text="Numéro payé", max_length=20),
        ),
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("success", "Succès"),
                    ("failed", "Échec"),
                    ("cancelled", "Annulé"),
                    ("expired", "Expiré"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
