# Generated by Django 5.2.13 on 2026-09-26 17:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_libelles_accentues"),
        ("subscriptions", "0006_libelles_accentues"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpayment",
            name="is_special_price",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Tarif spécial"
            ),
        ),
        migrations.CreateModel(
            name="PlanConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Gratuit"),
                            ("medium", "Medium"),
                            ("pro", "Pro"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Plan",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        help_text="FCFA entiers, envoyé tel quel à Orange Money (2000 = 2 000 FCFA).",
                        verbose_name="Prix (FCFA)",
                    ),
                ),
                (
                    "monthly_sales_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Vide = illimité.",
                        null=True,
                        verbose_name="Ventes par mois",
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        default=31, verbose_name="Durée (jours)"
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Liste de textes, ex. ["Page publique vendeur", "Commandes en ligne"]. La ligne du quota (« 10 ventes flash par mois ») est ajoutée automatiquement : ne pas la saisir.',
                        verbose_name="Fonctionnalités",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactif = plan non proposé à la souscription (Medium/Pro).",
                        verbose_name="Actif",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration de plan",
                "verbose_name_plural": "Configuration des plans",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="SellerPriceOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[("medium", "Medium"), ("pro", "Pro")],
                        max_length=20,
                        verbose_name="Plan",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        help_text="Entre 100 FCFA et le prix officiel du plan.",
                        verbose_name="Prix spécial (FCFA)",
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Vide = durée du plan. Ex. 1 pour un test de paiement.",
                        null=True,
                        verbose_name="Durée (jours)",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("test", "Test de paiement"),
                            ("pilote", "Vendeur pilote"),
                            ("partenaire", "Partenaire"),
                            ("promo", "Promotion"),
                        ],
                        max_length=20,
                        verbose_name="Motif",
                    ),
                ),
                (
                    "reason_detail",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Précision"
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Début"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Obligatoire, au plus 30 jours après le début.",
                        verbose_name="Fin",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Utilisations max"
                    ),
                ),
                (
                    "uses_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Incrémenté uniquement quand un paiement réussit (webhook).",
                        verbose_name="Utilisations",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_overrides",
                        to="accounts.sellerprofile",
                        verbose_name="Vendeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarif spécial vendeur",
                "verbose_name_plural": "Tarifs spéciaux vendeurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="subscriptionpayment",
            name="price_override",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="subscriptions.sellerpriceoverride",
                verbose_name="Tarif spécial",
            ),
        ),
        migrations.AddIndex(
            model_name="sellerpriceoverride",
            index=models.Index(
                fields=["seller", "plan", "is_active"],
                name="subscriptio_seller__48f24c_idx",
            ),
        ),
    ]
