# Generated by Django 5.2.13 on 2026-09-27 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_seed_plan_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooklog',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='Paiement associé (si trouvé) — vide pour un webhook orphelin', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='subscriptions.subscriptionpayment'),
        ),
    ]
