# Generated by Django 5.2.13 on 2026-07-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_migrate_shipped_to_out_for_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("confirmed", "Confirmé"),
                    ("out_for_delivery", "En livraison"),
                    ("delivered", "Livré et payé"),
                    ("cancelled", "Annulé"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
    ]
