# Generated by Django 5.2.13 on 2026-09-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Envoyée le"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("sent", "Envoyée"),
                    ("failed", "Échouée"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
