# Generated by Django 5.2.13 on 2026-09-20 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_seller_profile_bio_avatar_zones'),
        ('flash_sales', '0010_saleinterest_reminded_at'),
        ('products', '0004_alter_product_description_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, help_text='Prix applique pour cette vente. Vide = prix catalogue (Product.price).', max_digits=12, null=True, verbose_name='Prix promo')),
                ('display_order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, help_text="Permet de retirer un produit d'une vente sans le retirer du catalogue.", verbose_name='Actif dans cette vente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit de vente flash',
                'verbose_name_plural': 'Produits de vente flash',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_flash_s_3a2186_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, help_text="Nullable pour compat avec d'eventuelles lignes orphelines historiques (vente supprimee avant ce refactor) ; toujours renseigne pour les produits crees via l'application.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_catalog', to='accounts.sellerprofile', verbose_name='Vendeur'),
        ),
        migrations.AlterField(
            model_name='product',
            name='flash_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_products', to='flash_sales.flashsale'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['owner', 'is_active'], name='products_pr_owner_i_0d361b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx'),
        ),
        migrations.AddField(
            model_name='flashsaleproduct',
            name='flash_sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sale_products', to='flash_sales.flashsale', verbose_name='Vente flash'),
        ),
        migrations.AddField(
            model_name='flashsaleproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_sale_links', to='products.product', verbose_name='Produit'),
        ),
        migrations.AddIndex(
            model_name='flashsaleproduct',
            index=models.Index(fields=['flash_sale', 'is_active'], name='products_fl_flash_s_53eeab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flashsaleproduct',
            unique_together={('flash_sale', 'product')},
        ),
    ]
