# Generated by Django 5.2.13 on 2026-09-20 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_migrate_owner_and_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='flash_sale',
        ),
    ]
