# Generated by Django 5.2.13 on 2026-09-25 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_libelles_accentues"),
        ("products", "0007_remove_legacy_flash_sale_fk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productmedia",
            options={
                "ordering": ["order"],
                "verbose_name": "Média produit",
                "verbose_name_plural": "Médias produits",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="characteristics",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Caractéristiques"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Nullable pour compat avec d'éventuelles lignes orphelines historiques (vente supprimée avant ce refactor) ; toujours renseigné pour les produits créés via l'application.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products_catalog",
                to="accounts.sellerprofile",
                verbose_name="Vendeur",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                default="piece",
                help_text="pièce, kg, lot, carton...",
                max_length=50,
                verbose_name="Unité",
            ),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="media_type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Vidéo")],
                default="image",
                max_length=10,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Lien YouTube, TikTok ou autre",
                verbose_name="URL vidéo",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="price_delta",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Différence de prix",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("reservation", "Réservation (commande)"),
                    ("release", "Libération (annulation)"),
                    ("correction", "Correction manuelle"),
                    ("initial", "Stock initial"),
                ],
                max_length=20,
                verbose_name="Type de mouvement",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="quantity_change",
            field=models.IntegerField(
                help_text="Négatif = sortie, positif = entrée",
                verbose_name="Variation de stock",
            ),
        ),
    ]
