# Generated by Django 5.2.13 on 2026-09-26 12:54

from decimal import Decimal
from django.db import migrations, models


# Le FCFA n'a pas de centimes : on arrondit à l'unité (demi vers le haut) toute
# valeur fractionnaire existante AVANT de réduire decimal_places à 0, pour un
# résultat identique sur SQLite et PostgreSQL (qui arrondirait sinon lui-même).
TARGETS = [('products', 'FlashSaleProduct', ['promo_price']), ('products', 'Product', ['price']), ('products', 'ProductVariant', ['price_delta'])]


def arrondir_fcfa(apps, schema_editor):
    from decimal import ROUND_HALF_UP, Decimal

    for app_label, model_name, fields in TARGETS:
        model = apps.get_model(app_label, model_name)
        for obj in model.objects.all().only("pk", *fields).iterator():
            changed = {}
            for f in fields:
                value = getattr(obj, f)
                if value is None:
                    continue
                rounded = Decimal(value).quantize(Decimal("1"), rounding=ROUND_HALF_UP)
                if rounded != value:
                    changed[f] = rounded
            if changed:
                # update() plutôt que save() : pas de signaux ni d'auto_now.
                model.objects.filter(pk=obj.pk).update(**changed)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_libelles_accentues'),
    ]

    operations = [
        migrations.RunPython(arrondir_fcfa, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='flashsaleproduct',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Prix applique pour cette vente. Vide = prix catalogue (Product.price).', max_digits=12, null=True, verbose_name='Prix promo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Prix (FCFA)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_delta',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Différence de prix'),
        ),
    ]
