# Generated by Django 5.2.17 on 2026-09-30 08:35

import core.uploads
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_montants_fcfa_entiers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description_audio",
            field=models.FileField(
                blank=True,
                help_text="Enregistrement audio de la description (WebM/OGG)",
                null=True,
                upload_to=core.uploads.RandomUploadPath("audio/products"),
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("webm", "ogg", "mp3", "m4a", "wav")
                    ),
                    core.validators.MaxFileSizeValidator(5242880),
                    core.validators.validate_audio_content,
                ],
                verbose_name="Description vocale",
            ),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="file",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.uploads.RandomUploadPath("products/images"),
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("jpg", "jpeg", "png", "webp", "gif")
                    ),
                    core.validators.MaxFileSizeValidator(5242880),
                    core.validators.validate_image_content,
                ],
                verbose_name="Fichier image",
            ),
        ),
    ]
